Update docker-compose CICD with invoke commands
opsmill/infrahub pull request #3675
Opened 2024-06-17 14:32 UTC by BeArchiTek

New invoke commands to :
- generate the ENV variables from Infrahub Config with the default value (and update docker-compose file if needed)
- get the version from pyproject.toml and update docker-compose file

Rework CICD file to use the Bot token on stable branch and use the 2 new invoke commands

2024-06-17 14:37 UTC, BeArchiTek commented
@ogenstad I want to update the default *_ADDRESS for the container names instead of localhost as it's our default deployment. I want your point of view on it (it seems like we override the value everywhere for now)

2024-06-17 18:08 UTC, fatih-acar commented on tasks/dev.py
> +                    elif isinstance(default_value, (DatabaseType, StorageDriver, TraceExporterType, TraceTransportProtocol)):
I think you can directly do
```suggestion
                    elif isinstance(default_value, Enum):
```

and use `default_value.value`

2024-06-17 18:08 UTC, fatih-acar commented on docker-compose.yml
> +  INFRAHUB_INITIAL_AGENT_TOKEN:
This becomes empty, is this expected?

2024-06-18 08:41 UTC, ogenstad commented
> @ogenstad I want to update the default *_ADDRESS for the container names instead of localhost as it's our default deployment. I want your point of view on it (it seems like we override the value everywhere for now)

For me it would make most sense to keep `localhost` as that would always be usable for local testing, however `infrahub-server` would only make sense within the context of our Docker environment. If we are to remove localhost I think it would be better to just remove it and change these values to be required. So that you have to specify the server names. Forcing users to set these values would also make sense for the SDK.

I'm not sure we should keep the INFRAHUB_INTERNAL_ADDRESS, to me this is a duplicate that is only used to set INFRAHUB_ADDRESS used by the SDK. I think the only reason to keep it is if we should continue supporting infrahub.toml files but I'd vote to get rid of those.

2024-07-16 13:24 UTC, fatih-acar requested changes

2024-07-16 13:24 UTC, fatih-acar commented on tasks/dev.py
> +            new_config_lines.append(f'  {var}: "{default_value_str}"\n')
```suggestion
            new_config_lines.append(f'  {var}: ${{{var}:-{default_value_str}}}\n')
```

2024-07-16 13:24 UTC, fatih-acar commented on tasks/dev.py
> +                new_config_lines.append(f'  {var}: "{default_value_str}"\n')
```suggestion
                new_config_lines.append(f'  {var}: ${{{var}:-{default_value_str}}}\n')
```

2024-07-16 13:24 UTC, fatih-acar commented on tasks/dev.py
> +                    new_config_lines.append(f'  {var}: "{default_value_str}"\n')
```suggestion
                    new_config_lines.append(f'  {var}: ${{{var}:-{default_value_str}}}\n')
```

2024-07-16 13:24 UTC, fatih-acar commented on tasks/dev.py
> +                new_config_lines.append(f'  {var}: &{key_name} "{default_value_str}"\n')
```suggestion
                new_config_lines.append(f'  {var}: &{key_name} ${{{var}:-{default_value_str}}}\n')
```

2024-07-16 13:24 UTC, fatih-acar commented on tasks/dev.py
> +                new_config_lines.append(f'  {var}: &{key_name} "{existing_value}"\n')
```suggestion
                new_config_lines.append(f'  {var}: &{key_name} ${{{var}:-{existing_value}}}\n')
```

2024-07-16 14:12 UTC, fatih-acar commented on docker-compose.yml
> +      INFRAHUB_PRODUCTION: "false"
```suggestion
      INFRAHUB_PRODUCTION: ${INFRAHUB_PRODUCTION:-false}
```

2024-07-16 14:28 UTC, fatih-acar commented on docker-compose.yml
> +      INFRAHUB_LOG_LEVEL: "INFO"
```suggestion
      INFRAHUB_LOG_LEVEL: ${INFRAHUB_LOG_LEVEL:-INFO}
```

2024-07-16 14:28 UTC, fatih-acar commented on docker-compose.yml
> +      INFRAHUB_BROKER_ADDRESS: "message-queue"
```suggestion
      INFRAHUB_BROKER_ADDRESS: ${INFRAHUB_BROKER_ADDRESS:-message-queue}
```

2024-07-16 14:28 UTC, fatih-acar commented on docker-compose.yml
> +      INFRAHUB_CACHE_ADDRESS: "cache"
```suggestion
      INFRAHUB_CACHE_ADDRESS: ${INFRAHUB_CACHE_ADDRESS:-cache}
```

2024-07-16 14:28 UTC, fatih-acar commented on docker-compose.yml
> +      INFRAHUB_DB_ADDRESS: "database"
```suggestion
      INFRAHUB_DB_ADDRESS: ${INFRAHUB_DB_ADDRESS:-database}
```

2024-07-16 14:28 UTC, fatih-acar commented on docker-compose.yml
> +      INFRAHUB_PRODUCTION: "false"
```suggestion
      INFRAHUB_PRODUCTION: ${INFRAHUB_PRODUCTION:-false}
```

2024-07-16 14:28 UTC, fatih-acar commented on docker-compose.yml
> +      INFRAHUB_LOG_LEVEL: "DEBUG"
```suggestion
      INFRAHUB_LOG_LEVEL: ${INFRAHUB_LOG_LEVEL:-DEBUG}
```

2024-07-16 14:28 UTC, fatih-acar commented on docker-compose.yml
> +      INFRAHUB_ADDRESS: "http://infrahub-server:8000"
```suggestion
      INFRAHUB_ADDRESS: ${INFRAHUB_ADDRESS:-http://infrahub-server:8000}
```

2024-07-16 14:28 UTC, fatih-acar commented on docker-compose.yml
> +      INFRAHUB_INTERNAL_ADDRESS: "http://infrahub-server:8000"
```suggestion
      INFRAHUB_INTERNAL_ADDRESS: ${INFRAHUB_INTERNAL_ADDRESS:-http://infrahub-server:8000}
```

2024-07-16 14:28 UTC, fatih-acar commented on docker-compose.yml
> +      INFRAHUB_BROKER_ADDRESS: "message-queue"
```suggestion
      INFRAHUB_BROKER_ADDRESS: ${INFRAHUB_BROKER_ADDRESS:-message-queue}
```

2024-07-16 14:28 UTC, fatih-acar commented on docker-compose.yml
> +      INFRAHUB_CACHE_ADDRESS: "cache"
```suggestion
      INFRAHUB_CACHE_ADDRESS: ${INFRAHUB_CACHE_ADDRESS:-cache}
```

2024-07-16 14:28 UTC, fatih-acar commented on docker-compose.yml
> +      INFRAHUB_DB_ADDRESS: "database"
```suggestion
      INFRAHUB_DB_ADDRESS: ${INFRAHUB_DB_ADDRESS:-database}
```

2024-07-16 14:28 UTC, fatih-acar commented on docker-compose.yml
>        INFRAHUB_TIMEOUT: 20
```suggestion
      INFRAHUB_TIMEOUT: ${INFRAHUB_TIMEOUT:-20}
```

2024-07-16 14:28 UTC, fatih-acar commented on docker-compose.yml
> +      INFRAHUB_SECURITY_SECRET_KEY: ${INFRAHUB_SECURITY_SECRET_KEY-327f747f-efac-42be-9e73-999f08f86b92"}
```suggestion
      INFRAHUB_SECURITY_SECRET_KEY: ${INFRAHUB_SECURITY_SECRET_KEY:-327f747f-efac-42be-9e73-999f08f86b92"}
```

2024-07-16 14:28 UTC, fatih-acar commented on docker-compose.yml
> +      INFRAHUB_SECURITY_SECRET_KEY: ${INFRAHUB_SECURITY_SECRET_KEY-327f747f-efac-42be-9e73-999f08f86b92"}
```suggestion
      INFRAHUB_SECURITY_SECRET_KEY: ${INFRAHUB_SECURITY_SECRET_KEY:-327f747f-efac-42be-9e73-999f08f86b92"}
```

2024-07-16 14:29 UTC, fatih-acar approved these changes

2024-07-16 17:20 UTC, merged